// react/first-app/src/components/Weather.jsx
import React, { useState } from "react";
import axios from "axios";

const Weather = () => {
  const [city, setCity] = useState("");
  const [weatherData, setWeatherData] = useState({ weather: "", temp: "" });
  const [isvisible, setIsvisible] = useState(false);
  return (
    <div className="login">
      <span>Get Weather of your city</span>
      <form
        action=""
        method="get"
        className="form"
        onSubmit={(e) => {
          e.preventDefault();
          let key = process.env.REACT_APP_KEY;
          let url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${key}`;
          axios.get(url).then((response) => {
            setWeatherData({
              weather: response.data.weather[0].description,
              temp: response.data.main.temp - 273,
            });
            console.log(response.data);
          });

          setIsvisible(true);
          // setAllData([data]);
          console.log();
        }}
      >
        <input
          type="text"
          name="city"
          value={city}
          placeholder="Enter city name"
          onChange={(e) => {
            setCity(e.target.value);
          }}
        />
        <input type="submit" value="fetch weather"></input>
      </form>
      {isvisible && (
        <div>
          <span className="city">City: {city}</span>
          <br />
          <span className="Weather">Weather: {weatherData.weather}</span>
          <br />
          <span className="Tempreture">
            Tempreture: {Math.round(weatherData.temp)}
          </span>
        </div>
      )}
    </div>
  );
};

export default Weather;

// angular/second-angular-project/src/app/weather/weather.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-weather',
  templateUrl: './weather.component.html',
  styleUrls: ['./weather.component.css']
})
export class WeatherComponent {
  city!:string;
  weatherData!:any;
  visible!:boolean;

  constructor(private http:HttpClient){}

  fetchWeather(){
    let key = "138b91f7502c917df454a94449df5c18";
    this.http.get(`https://api.openweathermap.org/data/2.5/weather?q=${this.city}&appid=${key}`).subscribe((response)=>{
      console.log(response);
      this.weatherData = response;
      this.visible = true;
      // this.weat = res.weather.description;
      // this.temp = res.main.temp - 273;
    })
  }
}

<div class="container">
  <div>
    <h1>Know thy city Weather</h1>
    <form (ngSubmit)="fetchWeather()">
      <div class="form-group">
        <label for="city">City</label>
        <input
          type="text"
          class="form-control"
          id="city"
          name="city"
          placeholder="pune"
          [(ngModel)]="city"
          required
        />
      </div>
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
    <div class="details" *ngIf="visible">
      <span class="city">City: {{city}}</span>
      <br />
      <span class="Weather">Weather: {{weatherData.weather[0].description}}</span>
      <br />
      <span class="Tempreture">
        Tempreture: {{weatherData.main.temp - 273.15}}
      </span>
    </div>
  </div>
</div>
